### ISSUE TITLE
Missing thumbnails

### ISSUE THREAD

**Issue by JesusTheHun** [jeeftor/EmojiTaco#30]
The init process show `Starting background process` and then `Complete`.
The `img` directory is empty.

Trying again didn't solve the issue. I deleted the workflow directory, installed again, didn't solve the issue (I had installed an outdated version at first so I thought it was worth a shot).

The files `unicode.html` and `skin-tones.html` are empty - zero byte.

```
Alfred 5
MacOS 12.5
Python 3.9.13
```

**Comment by jeeftor** [comment]
Well Jesus the Hun...

Any chance you can post in the debug logs?

**Comment by JesusTheHun** [comment]
I did not include it because there is nothing valuable 😔

```
15:05:07 downloadDataFiles.py:126 INFO     Emoji Init Started
15:05:08 background.py:285 ERROR    [emoji_init] command failed with status 1
15:05:08 downloadDataFiles.py:126 INFO     Emoji Init Started
15:34:35 downloadDataFiles.py:126 INFO     Emoji Init Started
15:34:35 background.py:285 ERROR    [emoji_init] command failed with status 1
15:34:36 downloadDataFiles.py:126 INFO     Emoji Init Started
15:47:14 downloadDataFiles.py:126 INFO     Emoji Init Started
15:47:14 background.py:285 ERROR    [emoji_init] command failed with status 1
15:47:15 downloadDataFiles.py:126 INFO     Emoji Init Started
15:47:22 downloadDataFiles.py:126 INFO     Emoji Init Started
15:47:22 background.py:285 ERROR    [emoji_init] command failed with status 1
15:47:22 downloadDataFiles.py:126 INFO     Emoji Init Started
17:21:22 workflow.py:2391 INFO     checking for update ...
17:21:22 background.py:285 ERROR    [__workflow_update_check] command failed with status 1
17:21:32 workflow.py:2391 INFO     checking for update ...
17:21:32 background.py:285 ERROR    [__workflow_update_check] command failed with status 1
```

**Comment by jeeftor** [comment]
Yea... not so useful... the only question I guess I'd have is if you can run this from the command line directly? (if you know how to do that)

**Comment by JesusTheHun** [comment]
I'm not a python guy but I used IntelliJ to run the `main` of `bg_downloader.py`. 
There are undeclared dependencies like `Workflow3`. I installed it but it says it's compatibly with Alfred 3, not 4 & 5. Unfortunately it imports `cPickle` which is not available at the runtime and isn't available via `pip` either.
At this point I gave up.

Also, `pickle` isn't available with `python 3.9` because it's bundled (so I skipped it).

**Comment by jeeftor** [comment]
So cPickle existed only in Python2 and then it went away..

Are you using Py3 or Py2?

**Comment by jeeftor** [comment]
And are you running this build: https://github.com/jeeftor/EmojiTaco/releases/tag/v2.0.1

**Comment by JesusTheHun** [comment]
I used `python3.9`because version 2.0.2 says "python 3"

**Comment by jeeftor** [comment]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/6491743/185446555-ce0faaa1-3888-4f40-8fcb-153aefa24f0d.png">

Open in a terminal then run this command:

~`PYTHONPATH=$(pwd)/src/libs python3 src/downloadDataFiles.py`~

I mean this:

`PYTHONPATH=$(pwd)/src/libs python3 src/bg_downloader.py`

**Comment by jeeftor** [comment]
<img width="784" alt="image" src="https://user-images.githubusercontent.com/6491743/185446986-9572a8c3-3db2-46f4-84f2-e497c237f0b3.png">

If it works you'll see something like this...

**Comment by jeeftor** [comment]
The `PYTHONPATH` command tells it where to look for local libs

**Comment by JesusTheHun** [comment]
It downloads fine and then this happens : 

```
10:26:37 bg_downloader.py:47 INFO     Parsing Downloaded Files
10:26:37 bg_downloader.py:48 INFO     Creating DataFileBuilder
/Users/jonathan/Library/Application Support/Alfred 2/Workflow Data/org.jeef.emoji/aw-m_iwlrsv/Icon.iconset:Failed to generate ICNS.
10:26:38 workflow.py:2111 ERROR    iconset exited with 1
Traceback (most recent call last):
  File "/Users/jonathan/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4F081B84-2453-4B0F-9EAA-D7841578965A/src/libs/workflow/workflow.py", line 2104, in run
    func(self)
  File "/Users/jonathan/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4F081B84-2453-4B0F-9EAA-D7841578965A/src/bg_downloader.py", line 40, in main
    parseFiles()
  File "/Users/jonathan/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4F081B84-2453-4B0F-9EAA-D7841578965A/src/bg_downloader.py", line 54, in parseFiles
    parse_html_file(csv, "full-emoji-list.html", msg)
  File "/Users/jonathan/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4F081B84-2453-4B0F-9EAA-D7841578965A/src/bg_downloader.py", line 160, in parse_html_file
    notify(title="Emoji Taco", text=message, sound=None)
  File "/Users/jonathan/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4F081B84-2453-4B0F-9EAA-D7841578965A/src/libs/workflow/notify.py", line 196, in notify
    install_notifier()
  File "/Users/jonathan/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4F081B84-2453-4B0F-9EAA-D7841578965A/src/libs/workflow/notify.py", line 128, in install_notifier
    png_to_icns(workflow_icon, icon)
  File "/Users/jonathan/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4F081B84-2453-4B0F-9EAA-D7841578965A/src/libs/workflow/notify.py", line 282, in png_to_icns
    raise RuntimeError("iconset exited with %d" % retcode)
RuntimeError: iconset exited with 1
```

**Comment by jeeftor** [comment]
Wow... that's so almost helpful... :( ... I'll have to look into the code and see what's going on but at least its downloading

So here is what its supposed to look like... 
<img width="813" alt="image" src="https://user-images.githubusercontent.com/6491743/185649152-f5ef5943-0a19-4c5c-a9eb-e458fbbeddb1.png">

And your stuff is crashing somewhere in here:

<img width="578" alt="image" src="https://user-images.githubusercontent.com/6491743/185649712-e6fd6944-2eb3-4d83-88e9-31109ff591b2.png">

**Comment by jeeftor** [comment]
Just for kicks can you try to re-init the emoji from Alfred?

**Comment by abbaszpro** [comment]
Same issue as [JesusTheHun](https://github.com/JesusTheHun)

MacOS 12.3
Alfred 4.7
Python 3.10.4
![Screen Shot 2022-08-22 at 4 12 19 PM](https://user-images.githubusercontent.com/18553767/185907988-a2620631-1a93-463b-8f72-fa209910815c.jpg)

**Comment by jeeftor** [comment]
Actually as I look at that last one I wonder if it’s an issue with the notify module….

Which I could prob wrap in an exception…. 

I’ll try to get a release out today to test

**Comment by JesusTheHun** [comment]
After I ran in the terminal like you asked, and tried to init again from Alfred, now it says no "No emoji found". So weird just got weirder.

**Comment by JesusTheHun** [comment]
I ran the `bg_downloader.py` script from Intellij, this time adding the libs to the `PYTHONPATH`. It failed because the working dir was `src` and therefore it did not find the `img` directory. So I changed the working dir and then it ran fine. 
Both use the same version, `python 3.9.13`. 

I ran init again from Alfred, it failed as before. So it looks like it has nothing to do with your script per se, but indeed the notifier trying to create an icon for its notifications.

The `convert_image` function do not fail but it doesn't create the images either. I opened the `iconset` dir and the icons are not created, maybe that's why `iconutil` fails.
I executed the same `sips` command directly in my terminal and it created the icon.

I removed the `shell=True` from `src/libs/workflow/notify.py:231` and it works fine.
It doesn't work when I try from Alfred though, so I'm not sure I understand what's going on.

**Comment by jeeftor** [comment]
That isn't my code so I'm not 100% sure what's going on with the notify stuff.... Thanks for working on this ... I'm busy this week but can pick it up next week hopefully.

**Comment by jeeftor** [comment]
For the time being here is my `/img` directory if you want icons for now. [img.zip](https://github.com/jeeftor/EmojiTaco/files/9426178/img.zip)

**Comment by kelicia** [comment]
Hey all, giving Alfred notification allowance on my Mac fixed the missing thumbnails for me.
