### ISSUE TITLE
cannot search for emoji

### ISSUE THREAD

**Issue by rxng** [jeeftor/EmojiTaco#5]
this workflow doesn't seem to be searching for emoji:

"No emoji found
please try again"

```
11:20:13 workflow.py:2174 ERROR    u'Appl\u1d48'
Traceback (most recent call last):
  File "/Users/rxng/Sync/prefs/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B5013FC8-9963-456F-B348-FE24889CDE02/workflow/workflow.py", line 2167, in run
    func(self)
  File "buildDataFiles.py", line 106, in main
    apple = cols[headers[u'Applᵈ']].text
KeyError: u'Appl\u1d48'
```

**Comment by jeeftor** [comment]
Did you Initialize it?

**Comment by rxng** [comment]
Yes, I ran init emoji

**Comment by jeeftor** [comment]
I'll take a look now :) - its always possible that once again unicode changed their webpage format.

**Comment by jeeftor** [comment]
I made a new release - there was a change on unicode.org.  https://github.com/jeeftor/EmojiTaco/releases/tag/v0.9.35
